{% set name = "sardana-alba" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ALBA-Synchrotron/sardana-alba/archive/{{ version }}.tar.gz
  sha256: 2e3c35874168fea240084a527130ce0fb7320903e79a414ac0dd63ec0541db28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - sardana

test:
  imports:
    - sardana_alba
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ALBA-Synchrotron/sardana-alba
  summary: Sardana common ALBA plugins
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - ovallcorba
