{% set name = "sardana-alba" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ALBA-Synchrotron/sardana-alba/archive/{{ version }}.tar.gz
  sha256: 6adb923e36707aeebe600b7103505d722b99d0d97df1daa30a079af0e39a0f55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - sardana

test:
  imports:
    - sardana_alba
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ALBA-Synchrotron/sardana-alba
  summary: Sardana common ALBA plugins
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - ovallcorba
