{% set name = "sardana-alba" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ALBA-Synchrotron/sardana-alba/archive/{{ version }}.tar.gz
  sha256: ff4a9e1d82dfd639168974387f1de4d5bab2636e01764650afdfabe78b6186d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - sardana

test:
  imports:
    - sardana_alba
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ALBA-Synchrotron/sardana-alba
  summary: Sardana common ALBA plugins
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - ovallcorba
